const CATEGORIES = [
  { id: "food", name: "Mat og drikke", icon: "🍎" },
  { id: "home", name: "Hjem, klær og hverdagsliv", icon: "🏠" },
  { id: "people", name: "Mennesker, familie og kropp", icon: "👥" },
  { id: "nature", name: "Natur, dyr og vær", icon: "🌿" },
  { id: "city", name: "By, transport og reise", icon: "🚆" },
  { id: "time", name: "Tid, dager, måneder og tall", icon: "🕰️" },
  { id: "verbs", name: "Verb og aktiviteter", icon: "🚶" },
  { id: "adjectives", name: "Adjektiv og beskrivelser", icon: "🎨" },
  { id: "adverbs", name: "Adverb og småord", icon: "💬" },
  { id: "art", name: "Kunst og kultur", icon: "🖼️" },
  { id: "school", name: "Skole, språk og samfunn", icon: "📚" }
];

const VOCABULARY = [
  // Mat og drikke
  { id: "food-apple", category: "food", fr: "la pomme", no: ["eplet", "eple"] },
  { id: "food-bread", category: "food", fr: "le pain", no: ["brødet", "brød"] },
  { id: "food-cheese", category: "food", fr: "le fromage", no: ["osten", "ost"] },
  { id: "food-milk", category: "food", fr: "le lait", no: ["melken", "melk"] },
  { id: "food-water", category: "food", fr: "l’eau", no: ["vannet", "vann"], accept: ["l'eau"] },
  { id: "food-coffee", category: "food", fr: "le café", no: ["kaffen", "kaffe"] },
  { id: "food-tea", category: "food", fr: "le thé", no: ["teen", "te"] },
  { id: "food-wine", category: "food", fr: "le vin", no: ["vinen", "vin"] },
  { id: "food-meat", category: "food", fr: "la viande", no: ["kjøttet", "kjøtt"] },
  { id: "food-fish", category: "food", fr: "le poisson", no: ["fisken", "fisk"] },
  { id: "food-chicken", category: "food", fr: "le poulet", no: ["kyllingen", "kylling"] },
  { id: "food-egg", category: "food", fr: "l’œuf", no: ["egget", "egg"], accept: ["l'oeuf"] },
  { id: "food-rice", category: "food", fr: "le riz", no: ["risen", "ris"] },
  { id: "food-potato", category: "food", fr: "la pomme de terre", no: ["poteten", "potet"] },
  { id: "food-tomato", category: "food", fr: "la tomate", no: ["tomaten", "tomat"] },
  { id: "food-onion", category: "food", fr: "l’oignon", no: ["løken", "løk"], accept: ["l'oignon"] },
  { id: "food-carrot", category: "food", fr: "la carotte", no: ["gulroten", "gulrot"] },
  { id: "food-salad", category: "food", fr: "la salade", no: ["salaten", "salat"] },
  { id: "food-fruit", category: "food", fr: "le fruit", no: ["frukten", "frukt"] },
  { id: "food-vegetable", category: "food", fr: "le légume", no: ["grønnsaken", "grønnsak"] },
  { id: "food-orange", category: "food", fr: "l’orange", no: ["appelsinen", "appelsin"], accept: ["l'orange"] },
  { id: "food-strawberry", category: "food", fr: "la fraise", no: ["jordbæret", "jordbær"] },
  { id: "food-butter", category: "food", fr: "le beurre", no: ["smøret", "smør"] },
  { id: "food-sugar", category: "food", fr: "le sucre", no: ["sukkeret", "sukker"] },
  { id: "food-salt", category: "food", fr: "le sel", no: ["saltet", "salt"] },
  { id: "food-breakfast", category: "food", fr: "le petit-déjeuner", no: ["frokosten", "frokost"] },
  { id: "food-lunch", category: "food", fr: "le déjeuner", no: ["lunsjen", "lunsj"] },
  { id: "food-dinner", category: "food", fr: "le dîner", no: ["middagen", "middag"] },
  { id: "food-dessert", category: "food", fr: "le dessert", no: ["desserten", "dessert"] },
  { id: "food-bottle", category: "food", fr: "la bouteille", no: ["flasken", "flaske"] },
  { id: "food-cup", category: "food", fr: "la tasse", no: ["koppen", "kopp"] },
  { id: "food-glass", category: "food", fr: "le verre", no: ["glasset", "glass"] },

  // Hjem, klær og hverdagsliv
  { id: "home-house", category: "home", fr: "la maison", no: ["huset", "hjemmet"] },
  { id: "home-apartment", category: "home", fr: "l’appartement", no: ["leiligheten", "leilighet"], accept: ["l'appartement"] },
  { id: "home-room", category: "home", fr: "la pièce", no: ["rommet", "rom"] },
  { id: "home-kitchen", category: "home", fr: "la cuisine", no: ["kjøkkenet", "kjøkken"] },
  { id: "home-bedroom", category: "home", fr: "la chambre", no: ["soverommet", "soverom"] },
  { id: "home-bathroom", category: "home", fr: "la salle de bains", no: ["badet", "baderommet"] },
  { id: "home-door", category: "home", fr: "la porte", no: ["døren", "dør"] },
  { id: "home-window", category: "home", fr: "la fenêtre", no: ["vinduet", "vindu"] },
  { id: "home-table", category: "home", fr: "la table", no: ["bordet", "bord"] },
  { id: "home-chair", category: "home", fr: "la chaise", no: ["stolen", "stol"] },
  { id: "home-bed", category: "home", fr: "le lit", no: ["sengen", "seng"] },
  { id: "home-lamp", category: "home", fr: "la lampe", no: ["lampen", "lampe"] },
  { id: "home-key", category: "home", fr: "la clé", no: ["nøkkelen", "nøkkel"] },
  { id: "home-garden", category: "home", fr: "le jardin", no: ["hagen", "hage"] },
  { id: "home-shirt", category: "home", fr: "la chemise", no: ["skjorten", "skjorte"] },
  { id: "home-trousers", category: "home", fr: "le pantalon", no: ["buksa", "bukse"] },
  { id: "home-dress", category: "home", fr: "la robe", no: ["kjolen", "kjole"] },
  { id: "home-skirt", category: "home", fr: "la jupe", no: ["skjørtet", "skjørt"] },
  { id: "home-sweater", category: "home", fr: "le pull", no: ["genseren", "genser"] },
  { id: "home-coat", category: "home", fr: "le manteau", no: ["kåpen", "frakken"] },
  { id: "home-shoe", category: "home", fr: "la chaussure", no: ["skoen", "sko"] },
  { id: "home-hat", category: "home", fr: "le chapeau", no: ["hatten", "hatt"] },
  { id: "home-bag", category: "home", fr: "le sac", no: ["veska", "bagen"] },
  { id: "home-watch", category: "home", fr: "la montre", no: ["armbåndsuret", "klokka"] },
  { id: "home-soap", category: "home", fr: "le savon", no: ["såpen", "såpe"] },
  { id: "home-towel", category: "home", fr: "la serviette", no: ["håndkleet", "håndkle"] },
  { id: "home-phone", category: "home", fr: "le téléphone", no: ["telefonen", "telefon"] },
  { id: "home-money", category: "home", fr: "l’argent", no: ["pengene", "penger"], accept: ["l'argent"] },
  { id: "home-gift", category: "home", fr: "le cadeau", no: ["gaven", "gave"] },
  { id: "home-umbrella", category: "home", fr: "le parapluie", no: ["paraplyen", "paraply"] },

  // Mennesker, familie og kropp
  { id: "people-person", category: "people", fr: "la personne", no: ["personen", "person"] },
  { id: "people-woman", category: "people", fr: "la femme", no: ["kvinnen", "kvinne"] },
  { id: "people-man", category: "people", fr: "l’homme", no: ["mannen", "mann"], accept: ["l'homme"] },
  { id: "people-child", category: "people", fr: "l’enfant", no: ["barnet", "barn"], accept: ["l'enfant"] },
  { id: "people-mother", category: "people", fr: "la mère", no: ["moren", "mor"] },
  { id: "people-father", category: "people", fr: "le père", no: ["faren", "far"] },
  { id: "people-daughter", category: "people", fr: "la fille", no: ["datteren", "jenta"] },
  { id: "people-son", category: "people", fr: "le fils", no: ["sønnen", "sønn"] },
  { id: "people-sister", category: "people", fr: "la sœur", no: ["søsteren", "søster"], accept: ["la soeur"] },
  { id: "people-brother", category: "people", fr: "le frère", no: ["broren", "bror"] },
  { id: "people-friend", category: "people", fr: "l’ami / l’amie", no: ["vennen", "venn"], accept: ["l'ami", "l'amie", "l’ami", "l’amie"] },
  { id: "people-family", category: "people", fr: "la famille", no: ["familien", "familie"] },
  { id: "people-head", category: "people", fr: "la tête", no: ["hodet", "hode"] },
  { id: "people-face", category: "people", fr: "le visage", no: ["ansiktet", "ansikt"] },
  { id: "people-eye", category: "people", fr: "l’œil", no: ["øyet", "øye"], accept: ["l'oeil"] },
  { id: "people-nose", category: "people", fr: "le nez", no: ["nesen", "nese"] },
  { id: "people-mouth", category: "people", fr: "la bouche", no: ["munnen", "munn"] },
  { id: "people-ear", category: "people", fr: "l’oreille", no: ["øret", "øre"], accept: ["l'oreille"] },
  { id: "people-hair", category: "people", fr: "les cheveux", no: ["håret", "hår"] },
  { id: "people-hand", category: "people", fr: "la main", no: ["hånden", "hånd"] },
  { id: "people-arm", category: "people", fr: "le bras", no: ["armen", "arm"] },
  { id: "people-leg", category: "people", fr: "la jambe", no: ["beinet", "bein"] },
  { id: "people-foot", category: "people", fr: "le pied", no: ["foten", "fot"] },
  { id: "people-heart", category: "people", fr: "le cœur", no: ["hjertet", "hjerte"], accept: ["le coeur"] },
  { id: "people-health", category: "people", fr: "la santé", no: ["helsen", "helse"] },
  { id: "people-happy", category: "people", fr: "heureux / heureuse", no: ["glad", "lykkelig"], accept: ["heureux", "heureuse"] },
  { id: "people-sad", category: "people", fr: "triste", no: ["trist"] },
  { id: "people-angry", category: "people", fr: "fâché / fâchée", no: ["sint"], accept: ["fâché", "fâchée"] },
  { id: "people-afraid", category: "people", fr: "avoir peur", no: ["å være redd", "redd"] },
  { id: "people-tired", category: "people", fr: "fatigué / fatiguée", no: ["trøtt", "sliten"], accept: ["fatigué", "fatiguée"] },

  // Natur, dyr og vær
  { id: "nature-tree", category: "nature", fr: "l’arbre", no: ["treet", "tre"], accept: ["l'arbre"] },
  { id: "nature-flower", category: "nature", fr: "la fleur", no: ["blomsten", "blomst"] },
  { id: "nature-forest", category: "nature", fr: "la forêt", no: ["skogen", "skog"] },
  { id: "nature-mountain", category: "nature", fr: "la montagne", no: ["fjellet", "fjell"] },
  { id: "nature-sea", category: "nature", fr: "la mer", no: ["havet", "sjøen"] },
  { id: "nature-river", category: "nature", fr: "la rivière", no: ["elven", "elv"] },
  { id: "nature-lake", category: "nature", fr: "le lac", no: ["innsjøen", "innsjø"] },
  { id: "nature-beach", category: "nature", fr: "la plage", no: ["stranden", "strand"] },
  { id: "nature-sun", category: "nature", fr: "le soleil", no: ["sola", "sol"] },
  { id: "nature-moon", category: "nature", fr: "la lune", no: ["månen", "måne"] },
  { id: "nature-sky", category: "nature", fr: "le ciel", no: ["himmelen", "himmel"] },
  { id: "nature-rain", category: "nature", fr: "la pluie", no: ["regnet", "regn"] },
  { id: "nature-snow", category: "nature", fr: "la neige", no: ["snøen", "snø"] },
  { id: "nature-wind", category: "nature", fr: "le vent", no: ["vinden", "vind"] },
  { id: "nature-cloud", category: "nature", fr: "le nuage", no: ["skyen", "sky"] },
  { id: "nature-weather", category: "nature", fr: "le temps", no: ["været", "vær"] },
  { id: "nature-dog", category: "nature", fr: "le chien", no: ["hunden", "hund"] },
  { id: "nature-cat", category: "nature", fr: "le chat", no: ["katten", "katt"] },
  { id: "nature-horse", category: "nature", fr: "le cheval", no: ["hesten", "hest"] },
  { id: "nature-cow", category: "nature", fr: "la vache", no: ["kua", "ku"] },
  { id: "nature-sheep", category: "nature", fr: "le mouton", no: ["sauen", "sau"] },
  { id: "nature-bird", category: "nature", fr: "l’oiseau", no: ["fuglen", "fugl"], accept: ["l'oiseau"] },
  { id: "nature-butterfly", category: "nature", fr: "le papillon", no: ["sommerfuglen", "sommerfugl"] },
  { id: "nature-bee", category: "nature", fr: "l’abeille", no: ["bia", "bie"], accept: ["l'abeille"] },
  { id: "nature-rabbit", category: "nature", fr: "le lapin", no: ["kaninen", "kanin"] },
  { id: "nature-fox", category: "nature", fr: "le renard", no: ["reven", "rev"] },
  { id: "nature-bear", category: "nature", fr: "l’ours", no: ["bjørnen", "bjørn"], accept: ["l'ours"] },
  { id: "nature-duck", category: "nature", fr: "le canard", no: ["anda", "and"] },
  { id: "nature-warm", category: "nature", fr: "il fait chaud", no: ["det er varmt"] },
  { id: "nature-cold", category: "nature", fr: "il fait froid", no: ["det er kaldt"] },

  // By, transport og reise
  { id: "city-city", category: "city", fr: "la ville", no: ["byen", "by"] },
  { id: "city-street", category: "city", fr: "la rue", no: ["gata", "gate"] },
  { id: "city-square", category: "city", fr: "la place", no: ["torget", "plass"] },
  { id: "city-shop", category: "city", fr: "le magasin", no: ["butikken", "butikk"] },
  { id: "city-market", category: "city", fr: "le marché", no: ["markedet", "marked"] },
  { id: "city-restaurant", category: "city", fr: "le restaurant", no: ["restauranten", "restaurant"] },
  { id: "city-hotel", category: "city", fr: "l’hôtel", no: ["hotellet", "hotell"], accept: ["l'hotel", "l'hôtel"] },
  { id: "city-station", category: "city", fr: "la gare", no: ["jernbanestasjonen", "stasjonen"] },
  { id: "city-airport", category: "city", fr: "l’aéroport", no: ["flyplassen", "flyplass"], accept: ["l'aéroport"] },
  { id: "city-bank", category: "city", fr: "la banque", no: ["banken", "bank"] },
  { id: "city-pharmacy", category: "city", fr: "la pharmacie", no: ["apoteket", "apotek"] },
  { id: "city-hospital", category: "city", fr: "l’hôpital", no: ["sykehuset", "sykehus"], accept: ["l'hôpital"] },
  { id: "city-car", category: "city", fr: "la voiture", no: ["bilen", "bil"] },
  { id: "city-bus", category: "city", fr: "le bus", no: ["bussen", "buss"] },
  { id: "city-train", category: "city", fr: "le train", no: ["toget", "tog"] },
  { id: "city-bike", category: "city", fr: "le vélo", no: ["sykkelen", "sykkel"] },
  { id: "city-plane", category: "city", fr: "l’avion", no: ["flyet", "fly"], accept: ["l'avion"] },
  { id: "city-boat", category: "city", fr: "le bateau", no: ["båten", "båt"] },
  { id: "city-ticket", category: "city", fr: "le billet", no: ["billetten", "billett"] },
  { id: "city-map", category: "city", fr: "la carte", no: ["kartet", "kart"] },
  { id: "city-suitcase", category: "city", fr: "la valise", no: ["kofferten", "koffert"] },
  { id: "city-journey", category: "city", fr: "le voyage", no: ["reisen", "reise"] },
  { id: "city-holiday", category: "city", fr: "les vacances", no: ["ferien", "ferie"] },
  { id: "city-country", category: "city", fr: "le pays", no: ["landet", "land"] },
  { id: "city-north", category: "city", fr: "le nord", no: ["nord"] },
  { id: "city-south", category: "city", fr: "le sud", no: ["sør"] },
  { id: "city-left", category: "city", fr: "à gauche", no: ["til venstre"] },
  { id: "city-right", category: "city", fr: "à droite", no: ["til høyre"] },
  { id: "city-straight", category: "city", fr: "tout droit", no: ["rett fram"] },
  { id: "city-address", category: "city", fr: "l’adresse", no: ["adressen", "adresse"], accept: ["l'adresse"] },

  // Tid, dager, måneder og tall
  { id: "time-today", category: "time", fr: "aujourd’hui", no: ["i dag"], accept: ["aujourd'hui"] },
  { id: "time-tomorrow", category: "time", fr: "demain", no: ["i morgen"] },
  { id: "time-yesterday", category: "time", fr: "hier", no: ["i går"] },
  { id: "time-morning", category: "time", fr: "le matin", no: ["morgenen", "morgen"] },
  { id: "time-evening", category: "time", fr: "le soir", no: ["kvelden", "kveld"] },
  { id: "time-night", category: "time", fr: "la nuit", no: ["natta", "natt"] },
  { id: "time-week", category: "time", fr: "la semaine", no: ["uka", "uke"] },
  { id: "time-month", category: "time", fr: "le mois", no: ["måneden", "måned"] },
  { id: "time-year", category: "time", fr: "l’année", no: ["året", "år"], accept: ["l'annee", "l'année"] },
  { id: "time-monday", category: "time", fr: "lundi", no: ["mandag"] },
  { id: "time-tuesday", category: "time", fr: "mardi", no: ["tirsdag"] },
  { id: "time-wednesday", category: "time", fr: "mercredi", no: ["onsdag"] },
  { id: "time-thursday", category: "time", fr: "jeudi", no: ["torsdag"] },
  { id: "time-friday", category: "time", fr: "vendredi", no: ["fredag"] },
  { id: "time-saturday", category: "time", fr: "samedi", no: ["lørdag"] },
  { id: "time-sunday", category: "time", fr: "dimanche", no: ["søndag"] },
  { id: "time-spring", category: "time", fr: "le printemps", no: ["våren", "vår"] },
  { id: "time-summer", category: "time", fr: "l’été", no: ["sommeren", "sommer"], accept: ["l'été"] },
  { id: "time-autumn", category: "time", fr: "l’automne", no: ["høsten", "høst"], accept: ["l'automne"] },
  { id: "time-winter", category: "time", fr: "l’hiver", no: ["vinteren", "vinter"], accept: ["l'hiver"] },
  { id: "time-hour", category: "time", fr: "l’heure", no: ["timen", "klokkeslettet"], accept: ["l'heure"] },
  { id: "time-minute", category: "time", fr: "la minute", no: ["minuttet", "minutt"] },
  { id: "time-one", category: "time", fr: "un / une", no: ["én", "en"] , accept: ["un", "une"] },
  { id: "time-two", category: "time", fr: "deux", no: ["to"] },
  { id: "time-three", category: "time", fr: "trois", no: ["tre"] },
  { id: "time-four", category: "time", fr: "quatre", no: ["fire"] },
  { id: "time-five", category: "time", fr: "cinq", no: ["fem"] },
  { id: "time-ten", category: "time", fr: "dix", no: ["ti"] },
  { id: "time-hundred", category: "time", fr: "cent", no: ["hundre"] },
  { id: "time-first", category: "time", fr: "premier / première", no: ["første"], accept: ["premier", "première"] },

  // Verb og aktiviteter
  { id: "verb-be", category: "verbs", fr: "être", no: ["å være"] },
  { id: "verb-have", category: "verbs", fr: "avoir", no: ["å ha"] },
  { id: "verb-do", category: "verbs", fr: "faire", no: ["å gjøre", "å lage"] },
  { id: "verb-go", category: "verbs", fr: "aller", no: ["å dra", "å gå"] },
  { id: "verb-come", category: "verbs", fr: "venir", no: ["å komme"] },
  { id: "verb-see", category: "verbs", fr: "voir", no: ["å se"] },
  { id: "verb-look", category: "verbs", fr: "regarder", no: ["å se på"] },
  { id: "verb-hear", category: "verbs", fr: "entendre", no: ["å høre"] },
  { id: "verb-listen", category: "verbs", fr: "écouter", no: ["å lytte"] },
  { id: "verb-say", category: "verbs", fr: "dire", no: ["å si"] },
  { id: "verb-speak", category: "verbs", fr: "parler", no: ["å snakke"] },
  { id: "verb-read", category: "verbs", fr: "lire", no: ["å lese"] },
  { id: "verb-write", category: "verbs", fr: "écrire", no: ["å skrive"] },
  { id: "verb-understand", category: "verbs", fr: "comprendre", no: ["å forstå"] },
  { id: "verb-know", category: "verbs", fr: "savoir", no: ["å vite", "å kunne"] },
  { id: "verb-want", category: "verbs", fr: "vouloir", no: ["å ville"] },
  { id: "verb-can", category: "verbs", fr: "pouvoir", no: ["å kunne"] },
  { id: "verb-must", category: "verbs", fr: "devoir", no: ["å måtte", "å skulle"] },
  { id: "verb-like", category: "verbs", fr: "aimer", no: ["å like", "å elske"] },
  { id: "verb-eat", category: "verbs", fr: "manger", no: ["å spise"] },
  { id: "verb-drink", category: "verbs", fr: "boire", no: ["å drikke"] },
  { id: "verb-cook", category: "verbs", fr: "cuisiner", no: ["å lage mat"] },
  { id: "verb-buy", category: "verbs", fr: "acheter", no: ["å kjøpe"] },
  { id: "verb-pay", category: "verbs", fr: "payer", no: ["å betale"] },
  { id: "verb-work", category: "verbs", fr: "travailler", no: ["å arbeide", "å jobbe"] },
  { id: "verb-study", category: "verbs", fr: "étudier", no: ["å studere"] },
  { id: "verb-sleep", category: "verbs", fr: "dormir", no: ["å sove"] },
  { id: "verb-wake", category: "verbs", fr: "se réveiller", no: ["å våkne"] },
  { id: "verb-walk", category: "verbs", fr: "marcher", no: ["å gå til fots", "å gå"] },
  { id: "verb-run", category: "verbs", fr: "courir", no: ["å løpe"] },
  { id: "verb-swim", category: "verbs", fr: "nager", no: ["å svømme"] },
  { id: "verb-travel", category: "verbs", fr: "voyager", no: ["å reise"] },
  { id: "verb-open", category: "verbs", fr: "ouvrir", no: ["å åpne"] },
  { id: "verb-close", category: "verbs", fr: "fermer", no: ["å lukke"] },
  { id: "verb-wait", category: "verbs", fr: "attendre", no: ["å vente"] },
  { id: "verb-find", category: "verbs", fr: "trouver", no: ["å finne"] },

  // Adjektiv og beskrivelser
  { id: "adj-big", category: "adjectives", fr: "grand / grande", no: ["stor"], accept: ["grand", "grande"] },
  { id: "adj-small", category: "adjectives", fr: "petit / petite", no: ["liten"], accept: ["petit", "petite"] },
  { id: "adj-good", category: "adjectives", fr: "bon / bonne", no: ["god", "bra"], accept: ["bon", "bonne"] },
  { id: "adj-bad", category: "adjectives", fr: "mauvais / mauvaise", no: ["dårlig"], accept: ["mauvais", "mauvaise"] },
  { id: "adj-beautiful", category: "adjectives", fr: "beau / belle", no: ["vakker", "fin"], accept: ["beau", "belle"] },
  { id: "adj-ugly", category: "adjectives", fr: "laid / laide", no: ["stygg"], accept: ["laid", "laide"] },
  { id: "adj-new", category: "adjectives", fr: "nouveau / nouvelle", no: ["ny"], accept: ["nouveau", "nouvelle", "nouvel"] },
  { id: "adj-old", category: "adjectives", fr: "vieux / vieille", no: ["gammel"], accept: ["vieux", "vieille", "vieil"] },
  { id: "adj-young", category: "adjectives", fr: "jeune", no: ["ung"] },
  { id: "adj-easy", category: "adjectives", fr: "facile", no: ["enkel", "lett"] },
  { id: "adj-difficult", category: "adjectives", fr: "difficile", no: ["vanskelig"] },
  { id: "adj-fast", category: "adjectives", fr: "rapide", no: ["rask"] },
  { id: "adj-slow", category: "adjectives", fr: "lent / lente", no: ["langsom", "treg"], accept: ["lent", "lente"] },
  { id: "adj-long", category: "adjectives", fr: "long / longue", no: ["lang"], accept: ["long", "longue"] },
  { id: "adj-short", category: "adjectives", fr: "court / courte", no: ["kort"], accept: ["court", "courte"] },
  { id: "adj-heavy", category: "adjectives", fr: "lourd / lourde", no: ["tung"], accept: ["lourd", "lourde"] },
  { id: "adj-light", category: "adjectives", fr: "léger / légère", no: ["lett (ikke tung)"], accept: ["léger", "légère"] },
  { id: "adj-hot", category: "adjectives", fr: "chaud / chaude", no: ["varm"], accept: ["chaud", "chaude"] },
  { id: "adj-cold", category: "adjectives", fr: "froid / froide", no: ["kald"], accept: ["froid", "froide"] },
  { id: "adj-full", category: "adjectives", fr: "plein / pleine", no: ["full"], accept: ["plein", "pleine"] },
  { id: "adj-empty", category: "adjectives", fr: "vide", no: ["tom"] },
  { id: "adj-open", category: "adjectives", fr: "ouvert / ouverte", no: ["åpen"], accept: ["ouvert", "ouverte"] },
  { id: "adj-closed", category: "adjectives", fr: "fermé / fermée", no: ["stengt", "lukket"], accept: ["fermé", "fermée"] },
  { id: "adj-clean", category: "adjectives", fr: "propre", no: ["ren"] },
  { id: "adj-dirty", category: "adjectives", fr: "sale", no: ["skitten"] },
  { id: "adj-kind", category: "adjectives", fr: "gentil / gentille", no: ["snill", "vennlig"], accept: ["gentil", "gentille"] },
  { id: "adj-calm", category: "adjectives", fr: "calme", no: ["rolig"] },
  { id: "adj-interesting", category: "adjectives", fr: "intéressant / intéressante", no: ["interessant"], accept: ["intéressant", "intéressante"] },
  { id: "adj-important", category: "adjectives", fr: "important / importante", no: ["viktig"], accept: ["important", "importante"] },
  { id: "adj-different", category: "adjectives", fr: "différent / différente", no: ["forskjellig"], accept: ["différent", "différente"] },
  { id: "adj-same", category: "adjectives", fr: "même", no: ["samme"] },
  { id: "adj-red", category: "adjectives", fr: "rouge", no: ["rød"] },
  { id: "adj-blue", category: "adjectives", fr: "bleu / bleue", no: ["blå"], accept: ["bleu", "bleue"] },
  { id: "adj-green", category: "adjectives", fr: "vert / verte", no: ["grønn"], accept: ["vert", "verte"] },
  { id: "adj-yellow", category: "adjectives", fr: "jaune", no: ["gul"] },
  { id: "adj-black", category: "adjectives", fr: "noir / noire", no: ["svart"], accept: ["noir", "noire"] },
  { id: "adj-white", category: "adjectives", fr: "blanc / blanche", no: ["hvit"], accept: ["blanc", "blanche"] },

  // Adverb og småord
  { id: "adv-yes", category: "adverbs", fr: "oui", no: ["ja"] },
  { id: "adv-no", category: "adverbs", fr: "non", no: ["nei"] },
  { id: "adv-please", category: "adverbs", fr: "s’il vous plaît", no: ["vær så snill"], accept: ["s'il vous plaît", "s'il vous plait"] },
  { id: "adv-thanks", category: "adverbs", fr: "merci", no: ["takk"] },
  { id: "adv-always", category: "adverbs", fr: "toujours", no: ["alltid"] },
  { id: "adv-never", category: "adverbs", fr: "jamais", no: ["aldri"] },
  { id: "adv-often", category: "adverbs", fr: "souvent", no: ["ofte"] },
  { id: "adv-sometimes", category: "adverbs", fr: "parfois", no: ["noen ganger"] },
  { id: "adv-now", category: "adverbs", fr: "maintenant", no: ["nå"] },
  { id: "adv-soon", category: "adverbs", fr: "bientôt", no: ["snart"] },
  { id: "adv-late", category: "adverbs", fr: "tard", no: ["sent"] },
  { id: "adv-early", category: "adverbs", fr: "tôt", no: ["tidlig"] },
  { id: "adv-here", category: "adverbs", fr: "ici", no: ["her"] },
  { id: "adv-there", category: "adverbs", fr: "là-bas", no: ["der borte"] },
  { id: "adv-everywhere", category: "adverbs", fr: "partout", no: ["overalt"] },
  { id: "adv-together", category: "adverbs", fr: "ensemble", no: ["sammen"] },
  { id: "adv-well", category: "adverbs", fr: "bien", no: ["godt", "bra"] },
  { id: "adv-badly", category: "adverbs", fr: "mal", no: ["på en dårlig måte"] },
  { id: "adv-quickly", category: "adverbs", fr: "vite", no: ["fort", "raskt"] },
  { id: "adv-slowly", category: "adverbs", fr: "lentement", no: ["langsomt", "sakte"] },
  { id: "adv-very", category: "adverbs", fr: "très", no: ["veldig"] },
  { id: "adv-enough", category: "adverbs", fr: "assez", no: ["nok", "ganske"] },
  { id: "adv-too", category: "adverbs", fr: "trop", no: ["for mye", "for"] },
  { id: "adv-almost", category: "adverbs", fr: "presque", no: ["nesten"] },
  { id: "adv-more", category: "adverbs", fr: "plus", no: ["mer"] },
  { id: "adv-less", category: "adverbs", fr: "moins", no: ["mindre"] },
  { id: "adv-also", category: "adverbs", fr: "aussi", no: ["også"] },
  { id: "adv-because", category: "adverbs", fr: "parce que", no: ["fordi"] },
  { id: "adv-but", category: "adverbs", fr: "mais", no: ["men"] },
  { id: "adv-why", category: "adverbs", fr: "pourquoi", no: ["hvorfor"] },
  { id: "adv-how", category: "adverbs", fr: "comment", no: ["hvordan"] },
  { id: "adv-where", category: "adverbs", fr: "où", no: ["hvor"] },

  // Kunst og kultur
  { id: "art-art", category: "art", fr: "l’art", no: ["kunsten", "kunst"], accept: ["l'art"] },
  { id: "art-artist", category: "art", fr: "l’artiste", no: ["kunstneren", "kunstner"], accept: ["l'artiste"] },
  { id: "art-work", category: "art", fr: "l’œuvre", no: ["kunstverket", "verket"], accept: ["l'oeuvre"] },
  { id: "art-painting", category: "art", fr: "la peinture", no: ["maleriet", "maleri"] },
  { id: "art-drawing", category: "art", fr: "le dessin", no: ["tegningen", "tegning"] },
  { id: "art-sculpture", category: "art", fr: "la sculpture", no: ["skulpturen", "skulptur"] },
  { id: "art-photo", category: "art", fr: "la photographie", no: ["fotografiet", "fotografi"] },
  { id: "art-colour", category: "art", fr: "la couleur", no: ["fargen", "farge"] },
  { id: "art-form", category: "art", fr: "la forme", no: ["formen", "form"] },
  { id: "art-line", category: "art", fr: "la ligne", no: ["linjen", "linje"] },
  { id: "art-light", category: "art", fr: "la lumière", no: ["lyset", "lys"] },
  { id: "art-shadow", category: "art", fr: "l’ombre", no: ["skyggen", "skygge"], accept: ["l'ombre"] },
  { id: "art-canvas", category: "art", fr: "la toile", no: ["lerretet", "lerret"] },
  { id: "art-brush", category: "art", fr: "le pinceau", no: ["penselen", "pensel"] },
  { id: "art-pencil", category: "art", fr: "le crayon", no: ["blyanten", "blyant"] },
  { id: "art-paper", category: "art", fr: "le papier", no: ["papiret", "papir"] },
  { id: "art-wood", category: "art", fr: "le bois", no: ["treverket", "tre"] },
  { id: "art-clay", category: "art", fr: "l’argile", no: ["leiren", "leire"], accept: ["l'argile"] },
  { id: "art-museum", category: "art", fr: "le musée", no: ["museet", "museum"] },
  { id: "art-exhibition", category: "art", fr: "l’exposition", no: ["utstillingen", "utstilling"], accept: ["l'exposition"] },
  { id: "art-gallery", category: "art", fr: "la galerie", no: ["galleriet", "galleri"] },
  { id: "art-music", category: "art", fr: "la musique", no: ["musikken", "musikk"] },
  { id: "art-song", category: "art", fr: "la chanson", no: ["sangen", "sang"] },
  { id: "art-film", category: "art", fr: "le film", no: ["filmen", "film"] },
  { id: "art-theatre", category: "art", fr: "le théâtre", no: ["teateret", "teater"] },
  { id: "art-literature", category: "art", fr: "la littérature", no: ["litteraturen", "litteratur"] },
  { id: "art-book", category: "art", fr: "le livre", no: ["boka", "bok"] },
  { id: "art-poem", category: "art", fr: "le poème", no: ["diktet", "dikt"] },
  { id: "art-dance", category: "art", fr: "la danse", no: ["dansen", "dans"] },
  { id: "art-create", category: "art", fr: "créer", no: ["å skape"] },
  { id: "art-paint", category: "art", fr: "peindre", no: ["å male"] },
  { id: "art-draw", category: "art", fr: "dessiner", no: ["å tegne"] },

  // Skole, språk og samfunn
  { id: "school-school", category: "school", fr: "l’école", no: ["skolen", "skole"], accept: ["l'école"] },
  { id: "school-teacher", category: "school", fr: "le professeur", no: ["læreren", "lærer"] },
  { id: "school-student", category: "school", fr: "l’élève", no: ["eleven", "elev"], accept: ["l'eleve", "l'élève"] },
  { id: "school-class", category: "school", fr: "la classe", no: ["klassen", "klasse"] },
  { id: "school-lesson", category: "school", fr: "le cours", no: ["undervisningstimen", "kurset"] },
  { id: "school-task", category: "school", fr: "l’exercice", no: ["oppgaven", "øvelsen"], accept: ["l'exercice"] },
  { id: "school-question", category: "school", fr: "la question", no: ["spørsmålet", "spørsmål"] },
  { id: "school-answer", category: "school", fr: "la réponse", no: ["svaret", "svar"] },
  { id: "school-language", category: "school", fr: "la langue", no: ["språket", "språk"] },
  { id: "school-word", category: "school", fr: "le mot", no: ["ordet", "ord"] },
  { id: "school-sentence", category: "school", fr: "la phrase", no: ["setningen", "setning"] },
  { id: "school-text", category: "school", fr: "le texte", no: ["teksten", "tekst"] },
  { id: "school-notebook", category: "school", fr: "le cahier", no: ["skriveboka", "notatboka"] },
  { id: "school-pen", category: "school", fr: "le stylo", no: ["pennen", "penn"] },
  { id: "school-computer", category: "school", fr: "l’ordinateur", no: ["datamaskinen", "PC-en"], accept: ["l'ordinateur"] },
  { id: "school-news", category: "school", fr: "les nouvelles", no: ["nyhetene", "nyheter"] },
  { id: "school-newspaper", category: "school", fr: "le journal", no: ["avisen", "avis"] },
  { id: "school-radio", category: "school", fr: "la radio", no: ["radioen", "radio"] },
  { id: "school-television", category: "school", fr: "la télévision", no: ["fjernsynet", "TV-en"] },
  { id: "school-internet", category: "school", fr: "Internet", no: ["internett"] },
  { id: "school-society", category: "school", fr: "la société", no: ["samfunnet", "samfunn"] },
  { id: "school-government", category: "school", fr: "le gouvernement", no: ["regjeringen", "regjering"] },
  { id: "school-election", category: "school", fr: "l’élection", no: ["valget", "valg"], accept: ["l'election", "l'élection"] },
  { id: "school-law", category: "school", fr: "la loi", no: ["loven", "lov"] },
  { id: "school-work", category: "school", fr: "le travail", no: ["arbeidet", "arbeid"] },
  { id: "school-job", category: "school", fr: "le métier", no: ["yrket", "yrke"] },
  { id: "school-office", category: "school", fr: "le bureau", no: ["kontoret", "skrivebordet"] },
  { id: "school-meeting", category: "school", fr: "la réunion", no: ["møtet", "møte"] },
  { id: "school-country", category: "school", fr: "l’État", no: ["staten", "stat"], accept: ["l'etat", "l'État"] },
  { id: "school-freedom", category: "school", fr: "la liberté", no: ["friheten", "frihet"] }
];
